server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: instagram-messaging-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

instagram:
  api:
    base-url: ${INSTAGRAM_BASE_URL:https://graph.facebook.com/v18.0}
    access-token: ${INSTAGRAM_ACCESS_TOKEN}
    verify-token: ${INSTAGRAM_VERIFY_TOKEN}
    page-id: ${INSTAGRAM_PAGE_ID}

logging:
  level:
    com.uade.seminario: ${LOG_LEVEL:INFO}
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
