server:
  port: 8080

spring:
  application:
    name: instagram-messaging-api

# Configuración de Instagram API
instagram:
  api:
    # URL base de la Graph API de Meta
    base-url: https://graph.facebook.com/v18.0
    # Token de acceso de la página (obtener de Meta Developer Portal)
    access-token: ${INSTAGRAM_ACCESS_TOKEN:your-access-token-here}
    # Token de verificación para webhooks
    verify-token: ${INSTAGRAM_VERIFY_TOKEN:your-verify-token-here}
    # ID de la página de Instagram
    page-id: ${INSTAGRAM_PAGE_ID:your-page-id-here}

# Configuración de logging
logging:
  level:
    com.uade.seminario: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


